### PR TITLE
Readme: Fix repo URL

### PR DESCRIPTION
**Pull request by mightyiam**
BTW I use [auto-package](https://github.com/jmanero/auto-package).

### CODE REVIEW

**Comment by mightyiam** [comment]
BTW, registering github.com/verbose and github.com/helpers is genius.

**Comment by jonschlinkert** [comment]
thanks! 

> registering github.com/verbose and github.com/helpers is genius.

lol and thanks!

**Comment by jonschlinkert** [comment]
published 0.4.2. thanks!

**Comment by mightyiam** [comment]
Thank you.

**Comment by jonschlinkert** [comment]
thank you! I appreciate it

**Pull request merged**
